### ISSUE TITLE
JIRA v6.3.9 Issue update hanging

### ISSUE THREAD

**Issue by makc2ru** [rcarz/jira-client#121] opened 2016-01-26 14:24 UTC
BasicCredentials creds = new BasicCredentials("login", "password");
        JiraClient jira = new JiraClient("https://jira-test.artgroup.local", creds);

        Issue issue = jira.getIssue("ARTI-1846"); // OK

        issue.update()
                .field(Field.DESCRIPTION, "1111111")
                .execute(); // HANGING

Problem: infinity waiting on update!

**Comment by rcarz** [comment] 2016-05-30 19:37
How long does it hang for? I noticed you're using ".local" for a domain so it could potentially be a DNS issue. In any case, jira-client is just making an HTTP connection to your JIRA server so it's not likely to be an issue with the client itself. I'm going to close this for now, but feel free to re-open if it's still a problem.

**Closed by rcarz** 2016-05-30 19:37 UTC

**Comment by trieulieuf9** [comment] 2017-03-02 04:36
I am having that exact same problem. After running debugging, i think the problem is related to converting update fields to Json. It is not related to HTTP connection to JIRA, because when it is hanging, i tried to turn off my wifi and nothing change.

`Issue.this.restclient.put(Issue.getRestUri(Issue.this.key), req1); // hang at this line`
